import Navbar from "./navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "AegisDEX",
  description: "Generated by create next app",
};
const Navigation = () => {
  return <Navbar />;
};
export default Navigation;
